### ISSUE TITLE
external issue tracking

### ISSUE THREAD

**Issue by markjoshwel** [markjoshwel/surplus#82]
see if these can close before the 2024.0.0 release, tentative mid-end july  
(not tryna rush these, just tracking them in one place instead of remembering emails :D)

documentation (non-crucial):

- [x] https://github.com/adrienbrignon/mkdocs-exporter/issues/26
- [x] https://github.com/adrienbrignon/mkdocs-exporter/issues/27

nix-related (non-crucial):

- [x] https://github.com/NixOS/nixpkgs/issues/308121
- [ ] https://github.com/NixOS/nixpkgs/pull/320721
